apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  namespace: {{ .Values.image.namspace }}
  # https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#controller_summary
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx # Ensure using NGINX Ingress class
  # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration
  rules:
  - host:  api.tsc.vn # Replace with your desired host 34.126.164.80.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 30000
      # - path: /docs
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: {{ .Release.Name }}
      #       port:
      #         number: 30000
      # - path: /openapi.json
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: {{ .Release.Name }}
      #       port:
      #         number: 30000
      # - path: /predict
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: {{ .Release.Name }}
      #       port:
      #         number: 30000

        
      