apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-telegram-job
  namespace: infrastructure
spec:
  image: asia-southeast1-docker.pkg.dev/dongtd2/flink/flink-sentiment:v1.39 # Update image tag as needed
  flinkVersion: v1_19
  serviceAccount: flink
  flinkConfiguration:
    python.executable: /usr/bin/python3
    python.client.executable: /usr/bin/python3
    parallelism.default: 1
    restart-strategy: fixed-delay
    restart-strategy.fixed-delay.attempts: 3
    restart-strategy.fixed-delay.delay: 60s
    jobmanager.memory.process.size: 768m  # Increase to ensure sufficient Total Flink Memory
    jobmanager.memory.off-heap.size: 128m  # Explicitly set to default minimum
    jobmanager.memory.jvm.overhead.min: 192m  # Ensure minimum JVM overhead
    jobmanager.memory.jvm.overhead.max: 256m  # Allow some flexibility
  job:
    jarURI: local:///opt/flink/opt/flink-python_2.12-1.19.1.jar
    entryClass: "org.apache.flink.client.python.PythonDriver"
    args:
      - "-pyclientexec"
      - "/usr/bin/python3"
      - "-py"
      - "/opt/flink/usrlib/flink_job_telegram.py"
      - "--bootstrap"
      - "kafka-kafka-bootstrap.infrastructure.svc:9192"
      - "--topic"
      - "message_queue"
      # - "--telegram-bot-token"  
      # - "$(TELEGRAM_BOT_TOKEN)"   flink_job_telegram.py can not read env variable directly, so we need to pass it as argument
      # - "--telegram-chat-id"   > fail > flink_job_telegram.py read this variale as text
      # - "$(TELEGRAM_CHAT_ID)"
    parallelism: 1
    upgradeMode: stateless
    state: running
  jobManager:
    resource:
      memory: "768m"  # Match flinkConfiguration
      cpu: 0.1
    replicas: 1
  taskManager:
    resource:
      memory: "1024m"
      cpu: 0.1
    replicas: 1
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-secrets
                  key: bot-token
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: telegram-secrets
                  key: chat-id