apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-sentiment-job
  namespace: infrastructure
spec:
  image: asia-southeast1-docker.pkg.dev/dongtd2/flink/flink-sentiment:v1.20 # Update image tag as needed
  flinkVersion: v1_19
  serviceAccount: flink
  flinkConfiguration:
    python.executable: /usr/bin/python3
    python.client.executable: /usr/bin/python3
    parallelism.default: 1
    restart-strategy: fixed-delay
    restart-strategy.fixed-delay.attempts: 3
    restart-strategy.fixed-delay.delay: 60s
    # jobmanager.memory.process.size: 1024m  # Ensure sufficient total memory
    # jobmanager.memory.off-heap.size: 128m  # Explicitly set to default minimum
    # jobmanager.memory.jvm.overhead.min: 192m  # Ensure minimum JVM overhead
    # jobmanager.memory.jvm.overhead.max: 256m  # Allow flexibility
    # taskmanager.memory.process.size: 2048m  # Match resource.memory
    # taskmanager.memory.flink.size: 1280m  # Allocate sufficient Flink memory
    # taskmanager.memory.jvm.overhead.min: 192m  # Ensure minimum JVM overhead
    # taskmanager.memory.jvm.overhead.max: 384m  # Allow flexibility
  job:
    jarURI: local:///opt/flink/opt/flink-python_2.12-1.19.1.jar
    entryClass: "org.apache.flink.client.python.PythonDriver"
    args:
      - "-pyclientexec"
      - "/usr/bin/python3"
      - "-py"
      - "/opt/flink/usrlib/flink_job_sentiment.py"
      - "--bootstrap"
      - "kafka-kafka-bootstrap.infrastructure.svc:9192"
      - "--in-topic"
      - "cdc.public.product_reviews"
      - "--out-topic"
      - "message_queue"
      - "--model-url"
      - "http://tsc.model-serving.svc.cluster.local:30000/predict"
    parallelism: 1
    upgradeMode: stateless
    state: running
  jobManager:
    resource:
      memory: "1024m"
      cpu: 0.2
    replicas: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 0.2
    replicas: 2
  podTemplate:
    spec:
      containers:
        - name: flink-main-container