apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - name: https
      port: 9100
      targetPort: https
  selector:
    name: node-exporter
