pipeline {
    agent any

    options{
        // Max number of build logs to keep and days to keep
        buildDiscarder(logRotator(numToKeepStr: '5', daysToKeepStr: '5'))
        // Enable timestamp at each job in the pipeline
        timestamps()
    }

    environment{
        registry = 'dongtd6/dongtd6/airflow-job-scripts:v1.39' //Image id push to Docker Hub
        registryCredential = 'DockerHubPAT'    //Credential on Jenkins to login Docker Hub  
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    echo 'Checking out code from repository..'
                    checkout scm //Checkout code from the repository
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    echo 'Building image for deployment..'
                    dockerImage = docker.build(registry, "-f dags/Dockerfile .")
                    echo 'Pushing image to dockerhub..'
                    docker.withRegistry( '', registryCredential ) { 
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }
}